# Generated by Django 5.1.4 on 2024-12-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_question_text_question_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='option4',
        ),
    ]
